"""
Django settings for EcoReMart project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import MEDIA_ROOT
from django.contrib import staticfiles

import EcoReMartApp

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9sdd2yvqwi98)wd94sr(_9gym)m*=5#d4b%s-6!cednbpu^!gk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EcoReMartApp.apps.EcoremartappConfig',
    'rest_framework',
    'cloudinary',
    'cloudinary_storage',
    'corsheaders',
    'drf_yasg',
]
import os
import environ
env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))
import cloudinary
import cloudinary.uploader
import cloudinary.api
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': env("CLOUDINARY_API_KEY"),
    'API_SECRET': env("CLOUDINARY_API_SECRET"),
}


PAYOS_CLIENT_ID=env("PAYOS_CLIENT_ID")
PAYOS_API_KEY=env("PAYOS_API_KEY")
PAYOS_CHECKSUM_KEY=env("PAYOS_CHECKSUM_KEY")
PAYOS_ENVIRONMENT = "sandbox"
PAYOS_RETURN_URL = "http://localhost:3000/payment-success"
PAYOS_CANCEL_URL = "http://localhost:3000/payment-cancel"
cloudinary.config(
  cloud_name = env("CLOUDINARY_CLOUD_NAME"),
  api_key = env("CLOUDINARY_API_KEY"),
  api_secret = env("CLOUDINARY_API_SECRET")
)
MAPBOX_API_KEY = env("MAPBOX_API_KEY")
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'EcoReMartApp.authentication.FirebaseAuthentication',
    ),
}
AUTH_USER_MODEL = 'EcoReMartApp.User'
MEDIA_ROOT=f'{BASE_DIR}/EcoReMartApp/static/'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'EcoReMartApp.middleware.DisableAuthForSwaggerMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
ROOT_URLCONF = 'EcoReMart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "EcoReMartApp/../templates",
            BASE_DIR / "EcoReMartApp" / "EcoReMartApp/../templates",  # thêm dòng này
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',   # thêm (tùy chọn)
                'django.template.context_processors.static',  # thêm (tùy chọn)
            ],
        },
    },
]

WSGI_APPLICATION = 'EcoReMart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecoremart',
        'USER': 'root',
        'PASSWORD': '060204',
        'HOST': ''  # mặc định localhost
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

