# Generated by Django 5.2.4 on 2025-07-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.DeleteModel(
            name='ProductStatus',
        ),
    ]
