# Generated by Django 5.2.4 on 2025-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='EcoReMartApp.CartItem', to='EcoReMartApp.product'),
        ),
    ]
