# Generated by Django 5.2.4 on 2025-07-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0005_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
