# Generated by Django 5.2.4 on 2025-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
