# Generated by Django 5.2.4 on 2025-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash payment', 'Thanh toán tiền mặt'), ('online payment', 'Thanh Toán Online')], default='cash payment', max_length=20),
        ),
    ]
