# Generated by Django 5.2.4 on 2025-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0012_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
