# Generated by Django 5.2.4 on 2025-08-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0013_cartitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='users_used',
        ),
        migrations.AddField(
            model_name='voucher',
            name='order_used',
            field=models.ManyToManyField(blank=True, related_name='vouchers_used', to='EcoReMartApp.order'),
        ),
    ]
