# Generated by Django 5.2.4 on 2025-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0016_order_is_paid_order_paid_at_store_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
