# Generated by Django 5.2.4 on 2025-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0017_order_ship_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
