# Generated by Django 5.2.4 on 2025-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0021_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_calculated',
            field=models.BooleanField(default=False, verbose_name='Đã tính hoa hồng'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Hoa hồng platform'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5, verbose_name='Tỷ lệ hoa hồng (5%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Doanh thu store'),
        ),
        migrations.AddField(
            model_name='order',
            name='vietqr_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='vietqr_qr_url',
            field=models.URLField(blank=True, null=True, verbose_name='VietQR URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='vietqr_transfer_content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nội dung CK'),
        ),
    ]
