# Generated by Django 5.2.4 on 2025-08-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0022_order_commission_calculated_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commission_calculated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platform_commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platform_commission_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store_revenue',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vietqr_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vietqr_qr_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vietqr_transfer_content',
        ),
        migrations.AddField(
            model_name='order',
            name='payos_order_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='PayOS Order Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PayOS Paid At'),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='PayOS Payment URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_qr_code',
            field=models.URLField(blank=True, null=True, verbose_name='PayOS QR Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn')], default='pending', max_length=20, verbose_name='PayOS Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payos_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayOS Transaction ID'),
        ),
    ]
