# Generated by Django 5.2.4 on 2025-08-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoReMartApp', '0023_remove_order_commission_calculated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
